version: '3.7'

services:
  db:
    image: mysql
    container_name: citylog-mysql
    environment:
      MYSQL_DATABASE: citylogdb

  citylog:
    image: citylog-tomee
    container_name: citylog-tomee
    build: .
    ports:
      - "8888:8080"
    depends_on:
      - db
