-- MySQL Script generated by MySQL Workbench
-- mer 30 oct 2019 16:18:57 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema citylogdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citylogdb` DEFAULT CHARACTER SET utf8 ;
USE `citylogdb` ;

-- -----------------------------------------------------
-- Table `citylogdb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citylogdb`.`User` ;

CREATE TABLE IF NOT EXISTS `citylogdb`.`User` (
  `username` VARCHAR(100) NOT NULL,
  `passwordHash` CHAR(128) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citylogdb`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citylogdb`.`Country` ;

CREATE TABLE IF NOT EXISTS `citylogdb`.`Country` (
  `countryCode` VARCHAR(2) NOT NULL,
  `name` VARCHAR(60) NULL,
  PRIMARY KEY (`countryCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citylogdb`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citylogdb`.`City` ;

CREATE TABLE IF NOT EXISTS `citylogdb`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `fk_countryCode` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idCity`),
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`fk_countryCode`)
    REFERENCES `citylogdb`.`Country` (`countryCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_City_Country1_idx` ON `citylogdb`.`City` (`fk_countryCode` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `citylogdb`.`Visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citylogdb`.`Visit` ;

CREATE TABLE IF NOT EXISTS `citylogdb`.`Visit` (
  `fk_username` VARCHAR(50) NOT NULL,
  `fk_idCity` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`fk_username`, `fk_idCity`, `startDate`),
  CONSTRAINT `fk_User_has_City_User`
    FOREIGN KEY (`fk_username`)
    REFERENCES `citylogdb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_City_City1`
    FOREIGN KEY (`fk_idCity`)
    REFERENCES `citylogdb`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_User_has_City_City1_idx` ON `citylogdb`.`Visit` (`fk_idCity` ASC) VISIBLE;

CREATE INDEX `fk_User_has_City_User_idx` ON `citylogdb`.`Visit` (`fk_username` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
